#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.stlib(target = 'multifile_lib',
              use = 'default zcm testzcmtypes_cpp',
              source = 'multi_file.cpp',
              rpath = ctx.env.RPATH_zcm,
              install_path = None)

    ctx.program(target = 'dispatch_loop',
                use = 'default zcm',
                source = 'dispatch_loop.cpp',
                rpath = ctx.env.RPATH_zcm,
                install_path = None)
