#! /usr/bin/env python
import os

def build(ctx):
    ### XXX this should come from 'env'
    VERSION='1.0.0'

    def build_node_pkg(task):
        srcdir = os.path.dirname(task.inputs[0].abspath())
        blddir = task.generator.path.get_bld().abspath()
        task.exec_command('(cd %s && npm pack %s > /dev/null)' % (blddir, srcdir))

    ctx(rule = build_node_pkg,
        color = 'PINK',
        source = ctx.path.ant_glob('node/*'),
        target = 'zcm-'+VERSION+'.tgz')

    def build_client_pkg(task):
        inp = ' '.join(n.abspath() for n in task.inputs)
        out = task.outputs[0].abspath()
        cmd = 'cat %s > %s' % (inp, out)
        task.exec_command(cmd)

    ctx(rule = build_client_pkg,
        source = 'client/socket.io.js client/index.js',
        target = 'zcm-client.js')
