#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'pub',
                use = 'default zcm',
                source = 'pub.c example_t.c',
                install_path = None)

    ctx.program(target = 'sub',
                use = 'default zcm',
                source = 'sub.c example_t.c',
                install_path = None)
