#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'pub',
                use = 'default zcm examplezcmtypes_c',
                source = 'pub.c')

    ctx.program(target = 'sub',
                use = 'default zcm examplezcmtypes_c',
                source = 'sub.c')

    ctx.program(target = 'nblock-inproc',
                use = 'default zcm examplezcmtypes_c',
                source = 'nblock_inproc.c')
