#! /usr/bin/env python

def build(ctx):
    ctx.env.INCLUDES_zcm = [ctx.path.abspath()]
    ctx.shlib(target = 'zcm',
              includes = '.',
              use = 'default',
              lib = 'zmq',
              source = ctx.path.ant_glob('*.cpp *.c'))
    ctx.install_files('${PREFIX}/include/zcm', ['zcm.h', 'zcm_coretypes.h', 'zcm-cpp.hpp', 'zcm-cpp-impl.hpp'])
