#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.env.INCLUDES_zcm = [ctx.path.abspath()]
    ctx.shlib(target = 'zcm',
              use = ['default', 'zmq'],
              source = ctx.path.ant_glob('*.cpp *.c'))

    install_headers = ['zcm.h', 'eventlog.h', 'zcm_coretypes.h', 'zcm-cpp.hpp', 'zcm-cpp-impl.hpp']
    ctx.install_files('${PREFIX}/include/zcm', install_headers)
