#! /usr/bin/env python
import os

def build(ctx):
    ### XXX this should come from 'env'
    VERSION='1.0.0'

    def build_node_pkg(task):
        srcdir = os.path.dirname(task.inputs[0].abspath())
        blddir = task.generator.path.get_bld().abspath()
        task.exec_command('(cd %s && npm pack %s > /dev/null)' % (blddir, srcdir))

    ctx(rule = build_node_pkg,
        color = 'PINK',
        source = ctx.path.ant_glob('zcm/*'),
        target = 'zcm-'+VERSION+'.tgz')
