/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zcm_zcm_ZCMGenericSerialTransport */

#ifndef _Included_zcm_zcm_ZCMGenericSerialTransport
#define _Included_zcm_zcm_ZCMGenericSerialTransport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zcm_zcm_ZCMGenericSerialTransport
 * Method:    initializeNative
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_zcm_zcm_ZCMGenericSerialTransport_initializeNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     zcm_zcm_ZCMGenericSerialTransport
 * Method:    getTransportPtr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_zcm_zcm_ZCMGenericSerialTransport_getTransportPtr
  (JNIEnv *, jobject);

/*
 * Class:     zcm_zcm_ZCMGenericSerialTransport
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zcm_zcm_ZCMGenericSerialTransport_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
