#! /usr/bin/env python
# encoding: utf-8

import os

def build(ctx):
    ctx(name = 'pyzcm',
        target = 'zerocm',
        features = 'c cshlib pyext',
        source = 'zerocm.pyx',
        # PYTHON here for safety (mainly copying java). Seems to compile
        # fine when omitted as well, but better safe than....
        use = 'zcm PYTHON').init_pyext()
