#! /usr/bin/env python
# encoding: utf-8

import subprocess


def install_python_package(ctx):
    if ctx.cmd == 'install':
        with open("zcm/python/version.txt", "w") as fh:
            fh.write(ctx.env.VERSION)

        subprocess.check_call(['sudo', 'ldconfig'])
        subprocess.check_call([
            'pip3',
            'install',
            '--force-reinstall',
            '--upgrade',
            'zcm/python/'])
        subprocess.check_call([
            'pip',
            'install',
            '--force-reinstall',
            '--upgrade',
            'zcm/python/'])


def build(ctx):
    ctx.add_post_fun(install_python_package)

