#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'zcm-logplayer-gui',
                use = ['default', 'zcm', 'gtk4'],
                source = ctx.path.ant_glob('*.cpp'))
