#!/usr/bin/env python

def build(ctx):
    lang = ['c_stlib', 'c_shlib', 'cpp']
    if ctx.env.USING_JAVA:
        lang += ['java']
    if ctx.env.USING_NODEJS:
        lang += ['nodejs']
    if ctx.env.USING_PYTHON:
        lang += ['python']
    ctx.zcmgen(name    = 'testzcmtypes',
               source  = ctx.path.ant_glob('*.zcm'),
               lang    = lang,
               javapkg = 'test.zcmtypes')
