#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'zcm-csv-writer',
                use    = ['default', 'zcm', 'zcm_tools_util'],
                source = ctx.path.ant_glob('*.cpp'))
