#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'pub',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'Pub.cpp test.cpp')

    ctx.program(target = 'sub',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'Sub.cpp')

    ctx.program(target = 'pubsub',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'PubSub.cpp')

    ctx.program(target = 'inproc',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'Inproc.cpp')

    ctx.program(target = 'serial',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'Serial.cpp')
