#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'pub',
                use = 'default',
                lib = 'zcm',
                source = 'Pub.cpp',
                install_path = None)

    ctx.program(target = 'sub',
                use = 'default',
                lib = 'zcm',
                source = 'Sub.cpp',
                install_path = None)

    ctx.program(target = 'inproc',
                use = 'default',
                lib = 'zcm',
                source = 'Inproc.cpp',
                install_path = None)
