#! /usr/bin/env python
# encoding: utf-8

def configure(ctx):
    pass

def build(ctx):
    ctx(features="subst",
        source="zcm.pc.in",
        target="zcm.pc",
        install_path="${LIBDIR}/pkgconfig",
        PREFIX = ctx.env.PREFIX)

    if ctx.env.USING_ELF:
        ctx(features="subst",
            source="zcm-tools-util.pc.in",
            target="zcm-tools-util.pc",
            install_path="${LIBDIR}/pkgconfig",
            PREFIX = ctx.env.PREFIX)

    if ctx.env.USING_JAVA:
        ctx(features="subst",
            source="zcm-tools.pc.in",
            target="zcm-tools.pc",
            install_path="${LIBDIR}/pkgconfig",
            PREFIX = ctx.env.PREFIX)
