#!/bin/bash

####################################
# ZCM Bash Environment
####################################
## IMPORTANT: Avoid making any system-specific changes to this file
##    Any custom path configuration should be perfomed in the user's own
##    environment script (e.g. .bashrc) by using the "Tweakables" defined below
##
## *THINK VERY HARD ABOUT CHANGES IN THIS FILE*
##    Your actions have the potential to break *everyone*
##
##  Install instructions:
##     Add the following lines to the end of your .bashrc
##        export ZCM_HOME=/path/to/repo/root/dir
##        source $ZCM_HOME/config/zcm-env
##     Note: You must re-source your environment for the
##        changes to take effect

####################################
# Tweakables
####################################
## ZCM_HOME: path to repo root dir (MUST be set)

####################################
# Important Paths
####################################

if [ -z ${ZCM_HOME+x} ]; then
    echo "ERROR: Expected ZCM_HOME to be set!"
    return
fi

####################################
# Add Necessary Env Paths
####################################
export CLASSPATH=$CLASSPATH:/usr/local/share/java/zcm.jar
