#! /usr/bin/env python
# encoding: utf-8

import waflib

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def options(ctx):
    ctx.load('compiler_c')
    ctx.load('compiler_cxx')
    ctx.add_option('-s', '--symbols', dest='symbols', default=False, action='store_true',
                   help='Leave the debugging symbols in the resulting object files')
    ctx.add_option('-d', '--debug', dest='debug', default=False, action='store_true',
                   help='Compile all C/C++ code in debug mode: no optimizations and full symbols')

def configure(ctx):
    ctx.load('compiler_c')
    ctx.load('compiler_cxx')
    ctx.load('java')
    ctx.check_cfg(package='zcm', args='--cflags --libs', uselib_store='zcm')

    # There actually should be a way to pull the zcm.jar file out of pkg-config and stuff it
    # into the uselib_store, but I don't know a great way to do it at this point.
    ctx.check_java_class('zcm.zcm.ZCM')

def setup_environment(ctx):
    useOptimize = not waflib.Options.options.debug
    useSymbols = waflib.Options.options.debug or waflib.Options.options.symbols

    WARNING_FLAGS = ['-Wall', '-Werror', '-Wno-unused-function', '-Wno-format-zero-length']
    DEBUG_FLAGS = ['-g']
    OPT_FLAGS = ['-O3']
    ctx.env.CFLAGS_default   = ['-std=gnu99', '-fPIC'] + WARNING_FLAGS
    ctx.env.CXXFLAGS_default = ['-std=c++11', '-fPIC'] + WARNING_FLAGS
    if useOptimize:
        ctx.env.CFLAGS_default   += OPT_FLAGS
        ctx.env.CXXFLAGS_default += OPT_FLAGS
    if useSymbols:
        ctx.env.CFLAGS_default   += SYM_FLAGS
        ctx.env.CXXFLAGS_default += SYM_FLAGS

def build(ctx):
    setup_environment(ctx)
    ctx.recurse('c')
    ctx.recurse('cpp')
    ctx.recurse('java')
