#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx(name       = 'zcm',
        features   = 'javac jar',
        srcdir     = ['zcm'],
        outdir     = 'classes',  # path to output (for .class)
        basedir    = 'classes',  # basedir for jar
        destfile   = 'zcm.jar')
