#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.shlib(target     = 'zcmjni',
              uselib     = 'JAVA',
              use        = 'default',
              lib        = 'zcm',
              source     = ctx.path.ant_glob('jni/*.c'))

    ctx(name       = 'zcm',
        features   = 'javac jar',
        srcdir     = ['zcm'],
        outdir     = 'classes',  # path to output (for .class)
        basedir    = 'classes',  # basedir for jar
        destfile   = 'zcm.jar')
