#! /usr/bin/env python
# encoding: utf-8

import os

def build(ctx):

    def build_node_pkg(task):
        srcdir = os.path.dirname(task.inputs[0].abspath())
        blddir = task.generator.path.get_bld().abspath()
        task.exec_command('(cd %s && npm pack %s > /dev/null)' % (blddir, srcdir))

    # should add an install that does npm install -g
    ctx(rule = build_node_pkg,
        color = 'PINK',
        source = ctx.path.ant_glob('node/*'),
        target = 'zerocm-'+ctx.env.VERSION+'.tgz')

    ctx(rule = 'cp ${SRC} ${TGT}',
        source = 'client/zcm-client.js',
        target = 'zcm-client.js')
