#! /usr/bin/env python
# encoding: utf-8

import os

def build(ctx):

    def build_node_pkg(task):
        srcdir = os.path.dirname(task.inputs[0].abspath())
        blddir = task.generator.path.get_bld().abspath()
        task.exec_command('(cd %s && npm pack %s > /dev/null)' % (blddir, srcdir))

    # should add an install that does npm install -g
    ctx(rule = build_node_pkg,
        color = 'PINK',
        source = ctx.path.ant_glob('node/*'),
        target = 'zerocm-'+ctx.env.VERSION+'.tgz')

    def build_client_pkg(task):
        inp = ' '.join(n.abspath() for n in task.inputs)
        out = task.outputs[0].abspath()
        cmd = 'cat %s > %s' % (inp, out)
        task.exec_command(cmd)

    # RRR: socket.io.js shouldn't stored in our repo, when installed through npm, it
    #      contains the client side code that can be served fairly simply.
    #      see http://socket.io/get-started/chat/ for an easy example
    # RRR: This is anthony work. I think he was probably trying to get zcm to
    #      be a single client file, a single server file, and a single zcmtypes file
    # RRR: I think we should preference installing socket.io through npm and linking their file
    #      as specified by their todo. I've added comments in the node-client example index.html
    #      that shows how you do it (with a current install of socket.io)
    # RRR: also we should install this tarball in /usr/local/share/zcm or something (i suppose
    #      an npm install global would work too, but would rather keep internet-requiring commands
    #      out of the normal waf build
    ctx(rule = build_client_pkg,
        source = 'client/socket.io.js client/index.js',
        target = 'zcm-client.js')
