#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.recurse('util');
    ctx.recurse('logger');
    ctx.recurse('logplayer');
    ctx.recurse('bridge');
    ctx.recurse('repeater');
    ctx.recurse('spy-peek');

    if ctx.env.USING_ELF:
        ctx.recurse('spy-lite');
        ctx.recurse('indexer');
