#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.recurse('logger');
    ctx.recurse('logplayer');
    ctx.recurse('pipe');
    ctx.recurse('repeater');
    ctx.recurse('spy-lite');
    ctx.recurse('spy-peek');
