/* ZCM type definition class file
 * This file was automatically generated by zcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package zcmtypes;
 
import java.io.*;
import java.util.*;
import zcm.zcm.*;
 
public final class nested1 implements zcm.zcm.ZCMEncodable
{
    public zcmtypes.a A;
 
    public nested1()
    {
    }
 
    public static final long ZCM_FINGERPRINT;
    public static final long ZCM_FINGERPRINT_BASE = 0x0012345678014100L;
 
    static {
        ZCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(zcmtypes.nested1.class))
            return 0L;
 
        classes.add(zcmtypes.nested1.class);
        long hash = ZCM_FINGERPRINT_BASE
             + zcmtypes.a._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(ZCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.A._encodeRecursive(outs); 
 
    }
 
    public nested1(byte[] data) throws IOException
    {
        this(new ZCMDataInputStream(data));
    }
 
    public nested1(DataInput ins) throws IOException
    {
        if (ins.readLong() != ZCM_FINGERPRINT)
            throw new IOException("ZCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static zcmtypes.nested1 _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        zcmtypes.nested1 o = new zcmtypes.nested1();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.A = zcmtypes.a._decodeRecursiveFactory(ins);
 
    }
 
    public zcmtypes.nested1 copy()
    {
        zcmtypes.nested1 outobj = new zcmtypes.nested1();
        outobj.A = this.A.copy();
 
        return outobj;
    }
 
}

