#!/usr/bin/env python

def build(ctx):
    ctx.zcmgen(name         = 'examplezcmtype-juliapkgs',
               source       = ctx.path.ant_glob('**/*.zcm'),
               juliapkg     = 'example.zcmtypes',
               juliagenpkgs = True)

    ctx.zcmgen(name     = 'examplezcmtypes',
               source   = ctx.path.ant_glob('**/*.zcm', excl='little_endian_t.zcm'),
               lang     = ['c_stlib', 'c_shlib', 'cpp', 'java', 'python', 'nodejs', 'julia'],
               juliapkg = 'example.zcmtypes',
               javapkg  = 'example.zcmtypes')

    ctx.zcmgen(name         = 'examplezcmtypes-little-endian',
               source       = ctx.path.ant_glob('little_endian_t.zcm'),
               lang         = ['c_stlib', 'c_shlib', 'cpp', 'julia'],
               juliapkg     = 'example.zcmtypes',
               littleEndian = True)
