#!/usr/bin/env python

def build(ctx):
    ctx.zcmgen(name         = 'examplezcmtypes',
               source       = ctx.path.ant_glob('**/*.zcm', excl='little_endian_t.zcm'),
               lang         = ['c_stlib', 'c_shlib', 'cpp', 'java', 'python', 'nodejs', 'julia'],
               javapkg      = 'example.zcmtypes')

    ctx.zcmgen(name         = 'examplezcmtype-juliapkgs',
               source       = ctx.path.ant_glob('**/*.zcm'),
               juliagenpkgs = True)

    ctx.zcmgen(name         = 'examplezcmtypes-little-endian',
               source       = ctx.path.ant_glob('little_endian_t.zcm'),
               lang         = ['c_stlib', 'c_shlib', 'cpp', 'julia'],
               littleEndian = True)

    # Do the same thing, just with package prefix
    ctx.zcmgen(name         = 'examplezcmtypepfx-juliapkgs',
               source       = ctx.path.ant_glob('**/*.zcm'),
               pkgPrefix    = 'example.zcmtypes',
               juliapkg     = 'juliazcmtypes',
               juliagenpkgs = True)

    ctx.zcmgen(name         = 'examplezcmtypespfx',
               source       = ctx.path.ant_glob('**/*.zcm', excl='little_endian_t.zcm'),
               lang         = ['c_stlib', 'c_shlib', 'cpp', 'java', 'python', 'nodejs', 'julia'],
               pkgPrefix    = 'example.zcmtypes',
               juliapkg     = 'juliazcmtypes',
               javapkg      = 'javazcmtypes')

    ctx.zcmgen(name         = 'examplezcmtypespfx-little-endian',
               source       = ctx.path.ant_glob('little_endian_t.zcm'),
               lang         = ['c_stlib', 'c_shlib', 'cpp', 'julia'],
               pkgPrefix    = 'example.zcmtypes',
               juliapkg     = 'juliazcmtypes',
               littleEndian = True)
