#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.shlib(target = 'zcm',
              # Note: Had to make the include path one level up so that includes
              #       within this directory structure would match the structure
              #       of the installed files. Includes should be written as:
              #       #include "zcm/file.h".
              includes = '..',
              export_includes = '..',
              use = ['default', 'zmq'],
              source = ctx.path.ant_glob(['*.cpp', '*.c',
                                          'util/*.c', 'util/*.cpp',
                                          'transport/*.c', 'transport/*.cpp']))

    ## Collect files for Embedded
    ctx(rule = 'tar cfz ${TGT} ${SRC}',
        source = 'zcm.h zcm_coretypes.h transport.h nonblocking.h nonblocking.c',
        target = 'zcm-embed.tar.gz')

    ctx.install_files('${PREFIX}/include/zcm',
                      ['zcm.h', 'zcm_coretypes.h', 'transport.h', 'transport_registrar.h', 'url.h', 'eventlog.h',
                       'zcm-cpp.hpp', 'zcm-cpp-impl.hpp'])

    ctx.recurse('java');
    ctx.recurse('js');
