#ifndef _ZCM_TRANS_PACKETIZED_SERIAL_PROTOCOL_H
#define _ZCM_TRANS_PACKETIZED_SERIAL_PROTOCOL_H

#include <stddef.h>
#include <stdint.h>

#include "generic_serial_fletcher.h"

#define PACKETIZED_U8_BYTES (1)
#define PACKETIZED_U16_BYTES (2)
#define PACKETIZED_U32_BYTES (4)
#define PACKETIZED_MAX_BODY_BYTES ((size_t)UINT8_MAX)

#define PACKETIZED_HEADER_TYPE_OFFSET (0)
#define PACKETIZED_HEADER_TYPE_BYTES (PACKETIZED_U8_BYTES)
#define PACKETIZED_HEADER_SESSION_ID_OFFSET \
    (PACKETIZED_HEADER_TYPE_OFFSET + PACKETIZED_HEADER_TYPE_BYTES)
#define PACKETIZED_HEADER_SESSION_ID_BYTES (PACKETIZED_U16_BYTES)
#define PACKETIZED_HEADER_BODY_LEN_OFFSET \
    (PACKETIZED_HEADER_SESSION_ID_OFFSET + PACKETIZED_HEADER_SESSION_ID_BYTES)
#define PACKETIZED_HEADER_BODY_LEN_BYTES (PACKETIZED_U8_BYTES)
#define PACKETIZED_HEADER_BYTES \
    (PACKETIZED_HEADER_BODY_LEN_OFFSET + PACKETIZED_HEADER_BODY_LEN_BYTES)

#define PACKETIZED_DATA_PACKET_ID_OFFSET (0)
#define PACKETIZED_DATA_PACKET_ID_BYTES (PACKETIZED_U16_BYTES)
#define PACKETIZED_DATA_PAYLOAD_OFFSET \
    (PACKETIZED_DATA_PACKET_ID_OFFSET + PACKETIZED_DATA_PACKET_ID_BYTES)
#define PACKETIZED_DATA_OVERHEAD_BYTES (PACKETIZED_DATA_PAYLOAD_OFFSET)
#define PACKETIZED_MIN_DATA_PAYLOAD_BYTES (1)
#define PACKETIZED_MAX_PACKET_DATA_SIZE \
    (PACKETIZED_MAX_BODY_BYTES - PACKETIZED_DATA_OVERHEAD_BYTES)

#define PACKETIZED_METADATA_TOTAL_PACKETS_OFFSET (0)
#define PACKETIZED_METADATA_TOTAL_PACKETS_BYTES (PACKETIZED_U16_BYTES)
#define PACKETIZED_METADATA_PACKET_DATA_SIZE_OFFSET \
    (PACKETIZED_METADATA_TOTAL_PACKETS_OFFSET + PACKETIZED_METADATA_TOTAL_PACKETS_BYTES)
#define PACKETIZED_METADATA_PACKET_DATA_SIZE_BYTES (PACKETIZED_U8_BYTES)
#define PACKETIZED_METADATA_TOTAL_MESSAGE_SIZE_OFFSET \
    (PACKETIZED_METADATA_PACKET_DATA_SIZE_OFFSET + PACKETIZED_METADATA_PACKET_DATA_SIZE_BYTES)
#define PACKETIZED_METADATA_TOTAL_MESSAGE_SIZE_BYTES (PACKETIZED_U32_BYTES)
#define PACKETIZED_METADATA_CHECKSUM_OFFSET \
    (PACKETIZED_METADATA_TOTAL_MESSAGE_SIZE_OFFSET + PACKETIZED_METADATA_TOTAL_MESSAGE_SIZE_BYTES)
#define PACKETIZED_METADATA_CHECKSUM_BYTES (PACKETIZED_U16_BYTES)
#define PACKETIZED_METADATA_BODY_BYTES \
    (PACKETIZED_METADATA_CHECKSUM_OFFSET + PACKETIZED_METADATA_CHECKSUM_BYTES)

#define PACKETIZED_RETRANS_COUNT_OFFSET (0)
#define PACKETIZED_RETRANS_COUNT_BYTES (PACKETIZED_U8_BYTES)
#define PACKETIZED_RETRANS_IDS_OFFSET \
    (PACKETIZED_RETRANS_COUNT_OFFSET + PACKETIZED_RETRANS_COUNT_BYTES)
#define PACKETIZED_RETRANS_ID_BYTES (PACKETIZED_U16_BYTES)
#define PACKETIZED_RETRANS_BODY_BYTES(count) \
    (PACKETIZED_RETRANS_IDS_OFFSET + ((size_t)(count) * PACKETIZED_RETRANS_ID_BYTES))
#define PACKETIZED_RETRANS_MAX_IDS \
    ((PACKETIZED_MAX_BODY_BYTES - PACKETIZED_RETRANS_IDS_OFFSET) / PACKETIZED_RETRANS_ID_BYTES)

#define PACKETIZED_RETRANS_TIMEOUT_US (200000)
#define PACKETIZED_MAX_PACKETS ((size_t)UINT16_MAX)
#define PACKETIZED_DEFAULT_MAX_MESSAGE_SIZE (1024)
#define PACKETIZED_FLETCHER16_INIT (0xFFFFu)

typedef enum packetized_msg_type_t
{
    PACKETIZED_MSG_METADATA    = 1,
    PACKETIZED_MSG_DATA        = 2,
    PACKETIZED_MSG_RETRANS_REQ = 3,
} packetized_msg_type_t;

static inline size_t packetized_message_packet_count(size_t message_size,
                                                     uint8_t packet_data_size)
{
    if (packet_data_size == 0) return 0;
    if (message_size == 0) return 1;
    return (message_size + packet_data_size - 1u) / packet_data_size;
}

#endif /* _ZCM_TRANS_PACKETIZED_SERIAL_PROTOCOL_H */
