#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.program(target = 'generic-serial',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'SerialTransportTest.cpp generic_serial_transport.c')

    ctx.program(target = 'blocking-serial',
                use = 'default zcm examplezcmtypes_cpp',
                source = 'BlockingSerialTest.cpp')
