#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.env.LIB_dl = 'dl'
    ctx.stlib(target = 'zcm_tools_util',
              export_includes = "../",
              use = ['default', 'elf', 'dl'],
              source = ctx.path.ant_glob('*.cpp'))
