#! /usr/bin/env python

def build(ctx):
    ctx.program(target = 'zcm-gen',
                includes = '.',
                use = 'default',
                source = ctx.path.ant_glob('*.c *.cpp **/*.cpp'))
