#!/usr/bin/env python

def build(ctx):
    ctx.zcmgen(name    = 'testzcmtypes',
               source  = ctx.path.ant_glob('*.zcm'),
               lang    = ['c', 'cpp', 'java'],
               javapkg = 'test.zcmtypes')
